# Develop a number guessing game: The computer generates a random number, and the player has to guess it within a certain number of tries. Provide feedback to the player (e.g., "Too high!", "Too low!").
import random
num = random.randint(1,11)
tries=5
print(num)
for i in range(tries) :
    
    guess=int(input("ENTER THE NUMBER YOU GUESSED  : "))
    if(num==guess ):
        print(
            """ 
            yay! right guess
            you took thiss much tries:
            and this much tries were left :
        """)
        break
    else:
        print("oops wrong number now you have this much guess left : ",tries-i)

print("numb1er generated by the system was : ", num)
